language: node_js
node_js:
  - "10.6.0"
branches:
  only:
  - master
before_install:
    - export TZ='Asia/Shanghai' # 更改时区
install: yarn install
script: 
  - yarn run build
  - yarn run test
after_success:
  - yarn run coveralls